# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 900e30e68a283d62822a22b2cccd397ba185e72d21ea4c11f044875f6d0cd61eb23242a871424ec5c98d2e5cac50d49132a2b4ce3ce89ca0a1986420125688d0

test:
  secret_key_base: 18ac500e0c5b91d04332924fef59eca5092ae8e27c37e8ed73dc805470e57d9845ffd29ec71b9c6c0162b9401ab1683c03d06151a84ca77a08b9c7077215d2d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
